@baseUrl = http://localhost:5000/api
@authToken = {{login.response.body.token}}

### Register a new user
POST {{baseUrl}}/auth/register
Content-Type: application/json

{
  "username": "testuser",
  "email": "testuser@example.com",
  "password": "password123"
}

### Login
# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
  "email": "testuser@example.com",
  "password": "password123"
}

### Get user profile
GET {{baseUrl}}/users/profile
Authorization: Bearer {{authToken}}

### Create a new blog post
POST {{baseUrl}}/blogs
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "title": "My First Blog Post",
  "content": "This is the content of my first blog post."
}

### Get all blog posts
GET {{baseUrl}}/blogs

### Get latest blog post
GET {{baseUrl}}/blogs/latest

### Create a new comment on a blog post
POST {{baseUrl}}/comments
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "content": "This is a great post!",
  "blogId": "1"
}


### Get all comments for a specific blog post
GET {{baseUrl}}/comments/blog/1

### Delete a comment
DELETE {{baseUrl}}/comments/1
Authorization: Bearer {{authToken}}

### Submit a new application
# @name submitApplication
POST {{baseUrl}}/apply
Content-Type: application/json

{
  "firstName": "turca",
  "lastName": "said",
  "email": "nicosaid@gmail.com",
  "password": "securepassword123",
  "linkedinProfile": "https://www.linkedin.com/in/johndoe",
  "startupName": "TechInnovate",
  "shortDescription": "AI-powered sustainability solutions",
  "problemSolved": "We're addressing climate change through innovative AI technologies.",
  "sector": "CleanTech",
  "stage": "mvp",
  "hasInvestment": false,
  "seekingInvestment": true,
  "hasCustomers": false,
  "customersDetails": "",
  "links": "https://techinnovate.com",
  "founderContact": "John Doe, johndoe@techinnovate.com",
  "whyJoinLinkUp": "We believe LinkUp can provide the mentorship and resources we need to scale our impact.",
  "howHeardAboutLinkUp": "Through a recommendation from a fellow entrepreneur."
}

### Get all applications (Admin only)
GET {{baseUrl}}/admin/applications
Authorization: Bearer {{authToken}}

### Update application status (Admin only)
PUT {{baseUrl}}/admin/applications/1
Authorization: Bearer {{authToken}}
Content-Type: application/json

{
  "status": "accepted"
}